# Generated by Django 2.1 on 2018-09-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_click',
            new_name='goodclick',
        ),
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_content',
            new_name='goodcontent',
        ),
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_image',
            new_name='goodimage',
        ),
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_introduce',
            new_name='goodintroduce',
        ),
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_price',
            new_name='goodprice',
        ),
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_stock',
            new_name='goodstock',
        ),
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_title',
            new_name='goodtitle',
        ),
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_type',
            new_name='goodtype',
        ),
        migrations.RenameField(
            model_name='goodinfo',
            old_name='good_unit',
            new_name='goodunit',
        ),
        migrations.RenameField(
            model_name='typeinfo',
            old_name='type_title',
            new_name='typetitle',
        ),
    ]
